# use_logo如果為true, 需要在logo_image設置路徑
use_logo: false
logo_image:
# 使用路徑, 填寫檔案名即可(比如, logo_image: logo.png 指向 source/imgs/logo.png)
navbar_text:
# 如果沒有Logo, 則設置為false, 並且設置navbar_text(否則預設為站點標題, 最好進行設置)

# 必填, 設定小型設備展示背景圖, 指向source/imgs, 比如xs_bg_image: bg.png -> source/imgs/bg.png
xs_bg_image: xsbg.gif

# 必填, 個人頭像, 如果是路徑, 則指向source/imgs
# 也可以填http:// OR https:// url地址
author_image: avatar.jpg
#網站ICON
favicons: favicons.png

# 程式設計師模式, 適合於用該程式的愛好寫技術文章的人員, 默認不開啟
# 選擇開啟後將會改變article-excerpt, article-content等的顯示
programmer_mode: false

# 導航菜單
menu:
  # index
  - title: 首頁
    # 參照font-awesome官網的icon, 取後面一段(比如用fa-star這個圖示, 那麼這裡的icon就填star)
    icon: home
    url: /
  # archives
  - title: 歸檔
    icon: archive
    url: archives
  # categories
  - title: 分類
    icon: list
    url: categories
    dropdown: 10
    #dropdown為下拉菜單出現的項目最大數目(只限於tags和categorys)
    # 如果不想顯示下拉菜單, 則不要填寫, 即dropdown:
    # 具體效果可以看https://myau.moe
  # tags
  - title: 標籤
    icon: tags
    url: tags
    dropdown: 20
  # about, 這個實際上是自訂page, 後面的自訂page參照about樣式
  - title: 關於我
    icon: user
    url: about
  - title:  這個報廢啦
    icon: bug
    url: B

# 每篇文章的preview默認圖片
# 必填項(除非你每篇文章的front-matter都設置了preview屬性)
# 填寫: 可以放多張圖, 將隨機抽取作為預設的preview圖片
# 如果使用檔案名則對應目錄: source/imgs/preview, 比如 preview1.jpg -> source/imgs/preview/preview1.jpg
# 如果用url則填寫完整的url地址即可
default_preview:
  - preview1.jpg
  - preview2.jpg
  - preview3.jpg
  - preview4.jpg
  - preview5.jpg
  - preview6.jpg
  - preview7.jpg
  - preview8.jpg

# 側邊欄
sidebar:
  recent_comments: false   # 最新評論, 默認關閉, 可能需要自己進行模板配置
  hot_posts: false         # 最熱文章, 如果配置了下面的文章統計就可以使用該側邊欄, 否則設置為false
  recent_posts: true      # 最新文章, 默認開啟
  random_posts: true      # 隨機文章, 默認開啟
  tags: true              # 熱門標籤, 默認開啟
  friend_links: false      # 友情連結, 默認開啟
  links: true             # 個人連結, 默認開啟
  getMail: true         # 寄信, 默認開啟
  getGitHub: true     #取得commit紀錄

# 友情連結配置, 要先開啟上面的friend_links
friend_links:
  - name:
    link:
  - name:
    link:
  - name:
    link:

# 個人連結配置, 要先開啟上面的links
links:
  - name: 部屬於netlify的本網站
    link: https://tsuiokuyo.netlify.com/


# 是否使用公告
# 公告是什麼可以看https://myau.moe
# 如果使用了公告, 那麼公告內容需要自己去配置
# 在主題下的layout/_partial/issue.ejs進行內容修改
# 如果不用公告, 請設置此項為false
use_issue: true

# 背景圖功能
# 必填項
slide_background:
  # 預設為false, 即採用路徑圖片
  use_url: false
  # use_url: true情況下, 採用七牛外鏈空間的形式, 下面三個參數組合指向: http://ouo1ro65u.bkt.clouddn.com/background(1~10).png
  # prefix: http://ouo1ro65u.bkt.clouddn.com/background   七牛對象存儲空間外鏈主機地址和圖片名稱前綴
  # ext: png          圖片的後綴格式, 要求可供選擇的圖片都是統一後綴
  # max_count: 10     可供選擇的圖片數量, 背景圖會從這裡隨機抽取6張圖

  # use_url: false情況下, 採用本地部落格圖片路徑, 下面三個參數組合指向: source/imgs/slide/background(1~10).jpg
  prefix: slide/background
  ext: jpg
  max_count: 7


# 是否開啟歐尼醬功能
open_oni: false
# 歐尼醬功能設置, 前提為open_oni: true
oni_setting:
  # 限三項, 可以自己配置連結(一般是上面的menu或者自己的page)
  - title: 歸檔
    url: archives
  - title: 關於
    url: about
  - title: 留言板
    url: message
# 歐尼醬選項圖片(可以自己替換, 最好是100 * 100像素的圖片)
# 圖片為默認的 source/imgs/oni/oni(1~6).jpg
# 如果自己替換了不同後綴的圖片, 需要在 source/css/_common.css中修改(直接ctrl + F搜oni)


# 輸入特效activate-power-mode
# https://github.com/disjukr/activate-power-mode
power_mode:
  colorful: true
  shake: true

# 文章統計, 目前只支持leancloud(可能到時添加不蒜子統計)
# 獲取appId和appKey方法直接百度 or google(或者看這篇http://crescentmoon.info/2014/12/11/popular-widget/)
# 注意一旦生成新的文章就不要隨便改名了
leancloud:
  appid: h9skyMx8X0Y3Ig5woBbxkHDg-9Nh9j0Va
  # your appId
  appkey: 4nxlUeU9SeArO2IDB1glhupg
  # your appKey

# 評論系統, 目前只支持gitment(為了自訂樣式)
# 關於gitment如何配置看這篇 https://imsun.net/posts/gitment-introduction/
# 如果不用的話要把下面的use_comment設置為false
comment:
  gitment:
      owner: # 必填項, 你的GitHub ID
      repo: # 必填項  你的存儲評論的repo
      oauth:
        client_id:  # 必填項
        client_secret: # 必填項
        redirect_uri: # 可以填也可以不填

# 是否使用評論系統
use_comment: false

node_sass:
  outputStyle: compressed
  precision: 5
  sourceComments: false
