image: node:10.15.0

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - npm install hexo-generator-feed --save
  - npm install
  - hexo c
  - cd ./public
  - git init
  - git config --global user.email "Tsuiokuyo@gmail.com" ## git配置
  - git config --global user.name "Tsuiokuyo" ## git配置
  - git config --global push.default simple
 ##- git add .
 ##  - git commit -m "auto-deploy"
  artifacts:
    paths:
    - public
  only:
  - master
