image: node:10.15.0

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - npm install hexo-generator-feed --save
  - npm install
  - hexo g
  - cd ./public
  - git init
  - git config --global user.email "Tsuiokuyo@gmail.com" ## git配置
  - git config --global user.name "Tsuiokuyo" ## git配置 
  - git config --global push.default simple
  - git add .
  - git commit -m "auto-deploy"
 ## - git push --force --quiet --set-upstream https://9af212c2af751d3e16659a99227336d071145517@github.com/Tsuiokuyo/Tsuiokuyo.github.io.git master ## github仓库地址
  artifacts:
    paths:
    - public
  only:
  - master